version: '3'
services:
  web:
    build: ..
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  mongo_db:
    build:
      context: ..
      dockerfile: mongo-Dockerfile
    restart: always
    ports:
      - "27017:27017"
    volumes:

